# Generated by Django 6.0.2 on 2026-03-21 05:15

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('equipment_type', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('good', 'Tốt'), ('broken', 'Hỏng'), ('maintenance', 'Đang sửa')], max_length=20, null=True)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('local_x', models.IntegerField(blank=True, null=True)),
                ('local_y', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('default_severity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('species', models.TextField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('health_status', models.CharField(blank=True, choices=[('good', 'Tốt'), ('diseased', 'Bệnh'), ('dangerous', 'Nguy hiểm')], max_length=20, null=True)),
                ('planted_date', models.DateField(blank=True, null=True)),
                ('last_trimmed', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('equipment', 'Thiết bị'), ('tree', 'Cây xanh')], max_length=20)),
                ('equipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.equipment')),
                ('tree', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tree')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('level', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.building')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('open', 'Mở'), ('processing', 'Đang xử lý'), ('closed', 'Đã đóng')], max_length=20, null=True)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao')], max_length=20, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.asset')),
                ('incident_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.incidenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('repair', 'Sửa chữa'), ('inspection', 'Kiểm tra'), ('trim', 'Cắt tỉa'), ('replace', 'Thay thế')], max_length=20)),
                ('maintenance_date', models.DateField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.asset')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.appuser')),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.role'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('room_type', models.CharField(choices=[('classroom', 'Phòng học'), ('lab', 'Phòng thí nghiệm'), ('library', 'Thư viện'), ('office', 'Văn phòng'), ('hall', 'Hội trường')], max_length=20)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('blueprint_url', models.TextField(blank=True, null=True)),
                ('blueprint_width', models.IntegerField(blank=True, null=True)),
                ('blueprint_height', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.floor')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.room'),
        ),
    ]
