# Generated by Django 6.0.4 on 2026-04-25 15:47

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180, verbose_name="Tiêu đề")),
                ("content", models.TextField(verbose_name="Nội dung")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Đang hiển thị"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời gian đăng"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Thông báo trang giới thiệu",
                "verbose_name_plural": "Thông báo trang giới thiệu",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField(unique=True)),
                ("username", models.TextField(blank=True, null=True, unique=True)),
                ("password", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "app_user",
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "db_table": "building",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(unique=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("equipment_type", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("good", "Good"),
                            ("broken", "Broken"),
                            ("maintenance", "Maintenance"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("install_date", models.DateField(blank=True, null=True)),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("local_x", models.FloatField(blank=True, null=True)),
                ("local_y", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "equipment",
            },
        ),
        migrations.CreateModel(
            name="IncidentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(unique=True)),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "default_severity",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "applies_to",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("equipment", "Thiết bị"),
                                ("tree", "Cây xanh"),
                                ("facility", "Cơ sở vật chất"),
                                ("security", "An ninh"),
                                ("emergency", "Khẩn cấp"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                    ),
                ),
            ],
            options={
                "db_table": "incident_type",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
            options={
                "db_table": "role",
            },
        ),
        migrations.CreateModel(
            name="Tree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(unique=True)),
                ("species", models.TextField(blank=True, null=True)),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("good", "Good"),
                            ("diseased", "Diseased"),
                            ("dangerous", "Dangerous"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("planted_date", models.DateField(blank=True, null=True)),
                ("last_trimmed", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "db_table": "tree",
            },
        ),
        migrations.CreateModel(
            name="UniversityBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "db_table": "university_branch",
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("equipment", "Equipment"), ("tree", "Tree")],
                        max_length=20,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.equipment",
                    ),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.tree",
                    ),
                ),
            ],
            options={
                "db_table": "asset",
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "level",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        to="home.building",
                    ),
                ),
            ],
            options={
                "db_table": "floor",
            },
        ),
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("repair", "Repair"),
                            ("inspection", "Inspection"),
                            ("trim", "Trim"),
                            ("replace", "Replace"),
                        ],
                        max_length=20,
                    ),
                ),
                ("maintenance_date", models.DateField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.asset",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "maintenance",
            },
        ),
        migrations.CreateModel(
            name="PasswordResetCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField(db_index=True)),
                ("code_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "password_reset_code",
                "indexes": [
                    models.Index(
                        fields=["email", "consumed", "expires_at"],
                        name="password_re_email_f811a9_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="QuickIncidentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reporter_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField()),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="incidents/"),
                ),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("is_seen", models.BooleanField(default=False)),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quick_incident_reports",
                        to="home.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "quick_incident_report",
            },
        ),
        migrations.AddField(
            model_name="appuser",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.role",
            ),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("classroom", "Classroom"),
                            ("lab", "Lab"),
                            ("library", "Library"),
                            ("office", "Office"),
                            ("hall", "Hall"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "blueprint",
                    models.ImageField(
                        blank=True,
                        help_text="Hình ảnh sơ đồ / mặt bằng phòng (PNG, JPG…).",
                        null=True,
                        upload_to="room_blueprints/",
                        verbose_name="Sơ đồ phòng",
                    ),
                ),
                (
                    "blueprint_width",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tùy chọn, dùng khi hiển thị overlay trên bản đồ nội bộ.",
                        null=True,
                        verbose_name="Chiều rộng sơ đồ (px)",
                    ),
                ),
                (
                    "blueprint_height",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tùy chọn.",
                        null=True,
                        verbose_name="Chiều cao sơ đồ (px)",
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rooms",
                        to="home.floor",
                    ),
                ),
            ],
            options={
                "db_table": "room",
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "reported_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("open", "Open"),
                            ("processing", "Processing"),
                            ("closed", "Closed"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.asset",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.building",
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.floor",
                    ),
                ),
                (
                    "incident_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.incidenttype",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.room",
                    ),
                ),
            ],
            options={
                "db_table": "incident",
            },
        ),
        migrations.AddField(
            model_name="equipment",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment_set",
                to="home.room",
            ),
        ),
        migrations.AddField(
            model_name="tree",
            name="university_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trees",
                to="home.universitybranch",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="university_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buildings",
                to="home.universitybranch",
            ),
        ),
        migrations.AddField(
            model_name="appuser",
            name="university_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.universitybranch",
            ),
        ),
        migrations.AddConstraint(
            model_name="floor",
            constraint=models.UniqueConstraint(
                fields=("building", "name"), name="uniq_floor_name_per_building"
            ),
        ),
        migrations.AddConstraint(
            model_name="floor",
            constraint=models.UniqueConstraint(
                fields=("building", "level"), name="uniq_floor_level_per_building"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["geom"], name="idx_room_geom"),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("floor", "name"), name="uniq_room_name_per_floor"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(fields=["geom"], name="idx_incident_geom"),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(fields=["geom"], name="idx_equipment_geom"),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("equipment__isnull", False), ("tree__isnull", True)),
                    models.Q(("equipment__isnull", True), ("tree__isnull", False)),
                    _connector="OR",
                ),
                name="check_asset_type_exclusive",
            ),
        ),
        migrations.AddIndex(
            model_name="tree",
            index=models.Index(fields=["geom"], name="idx_tree_geom"),
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(fields=["geom"], name="idx_building_geom"),
        ),
    ]
