# Generated by Django 6.0.2 on 2026-02-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_fix_incidenttype_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Sẵn sàng sử dụng'), ('unavailable', 'Tạm ngưng sử dụng')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('equipment', 'Thiết bị'), ('tree', 'Cây xanh')], max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('good', 'Tốt'), ('broken', 'Hỏng'), ('maintenance', 'Đang sửa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Mở'), ('processing', 'Đang xử lý'), ('closed', 'Đã đóng')], max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.CharField(choices=[('repair', 'Sửa chữa'), ('inspection', 'Kiểm tra'), ('trim', 'Cắt tỉa'), ('replace', 'Thay thế')], max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('classroom', 'Phòng học'), ('lab', 'Phòng thí nghiệm'), ('library', 'Thư viện'), ('office', 'Văn phòng'), ('hall', 'Hội trường')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tree',
            name='health_status',
            field=models.CharField(choices=[('good', 'Tốt'), ('diseased', 'Bệnh'), ('dangerous', 'Nguy hiểm')], max_length=20),
        ),
    ]
