# Generated by Django 6.0.5 on 2026-05-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_appuser_must_change_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutannouncement',
            options={'ordering': ['-created_at', '-published_at'], 'verbose_name': 'Tin tức trang giới thiệu', 'verbose_name_plural': 'Tin tức trang giới thiệu'},
        ),
        migrations.AlterModelOptions(
            name='aboutfeaturedevent',
            options={'ordering': ['-created_at', '-published_at', '-event_date'], 'verbose_name': 'Sự kiện nổi bật', 'verbose_name_plural': 'Sự kiện nổi bật'},
        ),
    ]
