"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

# ... (Code cũ của bạn giữ nguyên) ...

# --- CẤU HÌNH GDAL ĐỘNG (TEAMWORK FRIENDLY) ---
if os.name == 'nt':
    # 1. Tự động lấy đường dẫn venv của người đang chạy lệnh
    # sys.prefix sẽ trả về: C:\Users\ACER\...\venv (trên máy bạn)
    # Hoặc: D:\Code\Project\venv (trên máy đồng nghiệp)
    VENV_BASE = Path(sys.prefix) 
    
    # Đường dẫn đến thư mục osgeo nơi pip cài đặt gói
    OSGEO_PATH = VENV_BASE / 'Lib' / 'site-packages' / 'osgeo'

    if OSGEO_PATH.exists():
        # 2. Bắt buộc: Đăng ký thư mục DLL với Windows (Python 3.8+)
        # Nếu thiếu dòng này, dù đường dẫn đúng thì Windows vẫn chặn không cho load DLL
        if hasattr(os, 'add_dll_directory'):
            try:
                os.add_dll_directory(str(OSGEO_PATH))
            except Exception:
                pass

        # 3. Thêm vào biến môi trường PATH
        os.environ['PATH'] = str(OSGEO_PATH) + ';' + os.environ['PATH']

        # 4. Tự động tìm tên file DLL chính xác (gdal308.dll, gdal309.dll...)
        # Giúp team member dùng version khác nhau vẫn chạy được
        gdal_lib_name = None
        for f in os.listdir(str(OSGEO_PATH)):
            # Tìm file bắt đầu bằng gdal, kết thúc bằng .dll và không phải gdal1xxx
            if f.startswith('gdal') and f.endswith('.dll') and '1' not in f[0:4]:
                gdal_lib_name = f
                break

        if gdal_lib_name:
            GDAL_LIBRARY_PATH = str(OSGEO_PATH / gdal_lib_name)
            GEOS_LIBRARY_PATH = str(OSGEO_PATH / 'geos_c.dll')
        else:
            print("⚠️ GDAL Warning: Không tìm thấy file DLL gdalxxx.dll trong osgeo")
    else:
        # Trường hợp máy đồng nghiệp chưa cài thư viện
        print(f"⚠️ GDAL Warning: Chưa cài đặt thư viện GDAL tại {OSGEO_PATH}")



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ozavqcbs_@5x8zy&&-cw!+%9hookrc2*56bpfft_l+mai^!fho'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'django.contrib.gis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'quan_ly_csht',
        'USER': 'postgres',
        'PASSWORD': '123',
        'HOST': 'localhost',
        'PORT': '5433',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# settings.py

# Sau khi login thành công, tự động nhảy về trang chủ (name='home' trong urls.py)
LOGIN_REDIRECT_URL = 'home' 

# Sau khi logout, nhảy về trang login (hoặc trang chủ tùy bạn)
LOGOUT_REDIRECT_URL = 'login'

